<template>
  <div class="report">
    <div class="status-container">
      <span id="status">
        <template v-if="store.isFinished">
          Execution Status: Finished.
          <span class="warning" v-if="store.finalStatus === 'fail'">Some tests failed.</span>
          <span class="warning" v-else>All tests passed.</span>
        </template>
        <template v-else>
          Execution Status: Running
        </template>
      </span>
      <span class="info">Generated by Gauge</span>
    </div>

    <StatsBar />

    <div class="specs">
      <SpecItem
        v-for="(spec, fileName) in store.specs"
        :key="fileName"
        :spec="spec"
      />
    </div>

    <div v-if="!connected" class="connecting">
      Connecting to server...
    </div>
  </div>
</template>

<script setup>
import { watch, ref } from 'vue'
import { useEventStore } from '../stores/eventStore'
import { useWebSocket } from '../composables/useWebSocket'
import StatsBar from '../components/StatsBar.vue'
import SpecItem from '../components/SpecItem.vue'

const store = useEventStore()

// 构建 WebSocket URL
const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
const wsUrl = `${wsProtocol}//${window.location.host}/api/events/stream`

const { events, isConnected, isFinished } = useWebSocket(wsUrl)
const connected = ref(false)

// 监听连接状态
watch(isConnected, (val) => {
  connected.value = val
})

// 监听新事件，同步到 store
watch(events, (newEvents) => {
  if (newEvents.length > 0) {
    const latest = newEvents[newEvents.length - 1]
    store.addEvent(latest)
  }
}, { deep: true })

// 监听结束状态
watch(isFinished, (val) => {
  if (val) {
    store.isFinished = true
  }
})
</script>

<style scoped>
.report {
  max-width: 1200px;
  margin: 0 auto;
}

.status-container {
  padding: 5px;
  font-weight: bolder;
}

.info {
  float: right;
  font-weight: 100;
}

.warning {
  color: grey;
  font-size: 12px;
  font-weight: 100;
}

.specs {
  margin-top: 10px;
}

.connecting {
  text-align: center;
  padding: 20px;
  color: #999;
}
</style>
