<template>
  <div class="report">
    <div class="status-container">
      <span id="status">
        <template v-if="store.isFinished">
          Execution Status: Finished.
          <span class="warning" v-if="store.failed">Some tests failed.</span>
          <span class="warning" v-else>All tests passed.</span>
          <span class="meta" v-if="store.durationText"> · {{ store.durationText }}</span>
        </template>
        <template v-else>
          Execution Status: Running
        </template>
      </span>
      <span class="info">
        Generated by Gauge{{ store.projectLabel }} on {{ store.timestamp }}
      </span>
    </div>

    <StatsBar />
    <ResultTable />

    <div v-if="!store.specList.length && store.isConnected" class="empty">
      Waiting for specification events…
    </div>
    <div v-if="!store.isConnected && !store.isFinished" class="connecting">
      Connecting to server…
    </div>
  </div>
</template>

<script setup>
import { onMounted, onUnmounted } from 'vue'
import { useReportStore } from '../stores/report'
import StatsBar from '../components/StatsBar.vue'
import ResultTable from '../components/ResultTable.vue'

const store = useReportStore()

onMounted(() => {
  store.fetchInfo()
  store.connect()
})

onUnmounted(() => {
  store.disconnect()
})
</script>

<style scoped>
.report {
  max-width: 1200px;
  margin: 0 auto;
}

.status-container {
  padding: 5px;
  font-weight: bolder;
}

.info {
  float: right;
  font-weight: 100;
}

.warning,
.meta {
  color: grey;
  font-size: 12px;
  font-weight: 100;
}

.empty,
.connecting {
  text-align: center;
  padding: 20px;
  color: #999;
}
</style>
