<template>
  <div class="report">
    <div class="status-container">
      <span id="status">
        <template v-if="store.isFinished">
          Execution Status: Finished.
          <span class="warning" v-if="store.finalStatus === 'fail'">Some tests failed.</span>
          <span class="warning" v-else>All tests passed.</span>
          <span class="meta" v-if="durationText"> · {{ durationText }}</span>
        </template>
        <template v-else>
          Execution Status: Running
        </template>
      </span>
      <span class="info">
        Generated by Gauge{{ projectLabel }} on {{ timestamp }}
      </span>
    </div>

    <StatsBar :all-expanded="allExpanded" @toggle-all="toggleAll" />

    <ul class="specs">
      <SpecItem
        v-for="spec in store.specList"
        :key="spec.id"
        :spec="spec"
        :force-expanded="allExpanded"
      />
    </ul>

    <div v-if="!store.specList.length && isConnected" class="empty">
      Waiting for specification events…
    </div>
    <div v-if="!isConnected && !store.isFinished" class="connecting">
      Connecting to server…
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useEventStore } from '../stores/eventStore'
import { useWebSocket } from '../composables/useWebSocket'
import StatsBar from '../components/StatsBar.vue'
import SpecItem from '../components/SpecItem.vue'

const store = useEventStore()
const allExpanded = ref(true)
const timestamp = ref('')
const infoProject = ref('')

const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
const wsUrl = `${wsProtocol}//${window.location.host}/api/events/stream`

const { isConnected } = useWebSocket(wsUrl, {
  onOpen: () => store.reset(),
  onEvent: (event) => store.addEvent(event)
})

const projectLabel = computed(() => {
  const name = store.projectName || infoProject.value
  return name ? ` · ${name}` : ''
})

const durationText = computed(() => {
  const ms = store.executionTime
  if (!ms) return ''
  if (ms < 1000) return `${ms} ms`
  return `${(ms / 1000).toFixed(2)} s`
})

function toggleAll() {
  allExpanded.value = !allExpanded.value
}

onMounted(async () => {
  try {
    const res = await fetch('/api/info')
    if (res.ok) {
      const info = await res.json()
      timestamp.value = info.timestamp || ''
      infoProject.value = info.project || ''
      if (info.project && !store.projectName) store.projectName = info.project
    }
  } catch {
    /* ignore */
  }
  if (!timestamp.value) {
    const d = new Date()
    const pad = (n) => String(n).padStart(2, '0')
    timestamp.value = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
  }
})
</script>

<style scoped>
.report {
  max-width: 1200px;
  margin: 0 auto;
}

.status-container {
  padding: 5px;
  font-weight: bolder;
}

.info {
  float: right;
  font-weight: 100;
}

.warning,
.meta {
  color: grey;
  font-size: 12px;
  font-weight: 100;
}

.specs {
  margin-top: 10px;
  margin-left: 0;
  padding-left: 0;
}

.empty,
.connecting {
  text-align: center;
  padding: 20px;
  color: #999;
}
</style>
